import './globals.css'
import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'
import Link from 'next/link'

const koulen = Koulen({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata: Metadata = {
  title: 'STUDIO CLIP',
  description: 'Generated by JUNO',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="my">
      <body>
        <header>
          <Link href='/'>
            <h1 className={`${koulen.className} mainTitle`}>STUDIO CLIP</h1>
          </Link>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  )
}
