import './globals.css'
import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'

const koulen = Koulen({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata: Metadata = {
  title: 'STUDIO CLIP',
  description: 'Generated by JUNO',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="my">
      <body className={koulen.className}>{children}</body>
    </html>
  )
}
